from math import atan2, cos, radians, sin, sqrt

### Shared Display Roots ###

# Base screen size for each jumbotron or diamond panel.
SCREEN_W = 480
SCREEN_H = 320

# Full application surface size across all three panels.
FULL_SCREEN_W = 3 * SCREEN_W
FULL_SCREEN_H = SCREEN_H

# Panel origins within the full application surface.
LEFT_JUMBOTRON_POS = (0, 0)
RIGHT_JUMBOTRON_POS = (SCREEN_W, 0)
DIAMOND_POS = (2 * SCREEN_W, 0)

# Shared menu labels and layout.
MAIN_MENU_ITEMS: list[str] = ["Games", "Player Stats", "Settings"]
TABS: list[str] = ["Finished", "Live", "Upcoming"]
TAB_STATUSES: list[str] = ["Final", "Live", "Preview"]
MENU_TAB_HEIGHT = 30
MENU_ROW_HEIGHT = 28
MENU_NUM_ROWS = (SCREEN_H - MENU_TAB_HEIGHT) // MENU_ROW_HEIGHT
MENU_FONT_SIZE = 18

# Shared palette primitives used across display components.
COLOR_BG: tuple[int, int, int] = (20, 20, 20)
COLOR_TAB_ACTIVE: tuple[int, int, int] = (60, 60, 180)
COLOR_TAB_INACTIVE: tuple[int, int, int] = (40, 40, 40)
COLOR_ROW_EVEN: tuple[int, int, int] = (30, 30, 30)
COLOR_ROW_ODD: tuple[int, int, int] = (38, 38, 38)
COLOR_ROW_HOVER: tuple[int, int, int] = (70, 70, 100)
COLOR_TEXT: tuple[int, int, int] = (220, 220, 220)
COLOR_FIELD: tuple[int, int, int] = (0, 100, 0)
COLOR_INFIELD: tuple[int, int, int] = (0xD8, 0xB8, 0x63)
COLOR_LINEUP_ACTIVE_BG: tuple[int, int, int] = (70, 65, 15)
COLOR_SCOREBOARD_HEADER_BG: tuple[int, int, int] = (50, 50, 50)
COLOR_SCOREBOARD_AWAY_BG: tuple[int, int, int] = (25, 25, 40)
COLOR_SCOREBOARD_HOME_BG: tuple[int, int, int] = (40, 25, 25)
COLOR_SCOREBOARD_RHE_BG: tuple[int, int, int] = (45, 45, 80)
COLOR_SCOREBOARD_DIMMED: tuple[int, int, int] = (120, 120, 120)
COLOR_SCOREBOARD_ACTIVE_BORDER: tuple[int, int, int] = (255, 220, 0)
COLOR_DIVIDER: tuple[int, int, int] = (60, 60, 60)
COLOR_NUMBER_BADGE_AWAY_BG: tuple[int, int, int] = (180, 50, 50)
COLOR_NUMBER_BADGE_HOME_BG: tuple[int, int, int] = (50, 90, 190)
COLOR_NUMBER_BADGE_FG: tuple[int, int, int] = (255, 255, 255)

# Left jumbotron panel layout — shared across scoreboard, pitch display, and PA events panels.
# SCOREBOARD_BSO_PANEL_W and SCOREBOARD_H are defined here (not in the Scoreboard section)
# because PITCH_DISPLAY and PA_EVENTS depend on them and appear earlier in this file.
SCOREBOARD_BSO_PANEL_W = 130
SCOREBOARD_H = 148  # = SCOREBOARD_HEADER_HEIGHT(28) + 2 × SCOREBOARD_TEAM_COL_W(60)
PITCHER_AREA_W = SCREEN_W - SCOREBOARD_BSO_PANEL_W
PITCHER_AREA_H = SCREEN_H - SCOREBOARD_H
PITCH_PANEL_W = 112
PA_EVENTS_W = PITCHER_AREA_W - PITCH_PANEL_W

### Field ###

# Shared screen roots aliased for field-only consumption.
FIELD_SCREEN_W = SCREEN_W
FIELD_SCREEN_H = SCREEN_H
FIELD_COLOR_BG = COLOR_BG
FIELD_COLOR_FIELD = COLOR_FIELD
FIELD_COLOR_INFIELD = COLOR_INFIELD
FIELD_COLOR_NUMBER_BADGE_AWAY_BG = COLOR_NUMBER_BADGE_AWAY_BG
FIELD_COLOR_NUMBER_BADGE_HOME_BG = COLOR_NUMBER_BADGE_HOME_BG
FIELD_COLOR_NUMBER_BADGE_FG = COLOR_NUMBER_BADGE_FG

# Geometry math roots for diamond and statcast hit conversion.
FIELD_SQRT_2 = sqrt(2)
FIELD_ACTUAL_DIAMOND_SIZE_FT = 90.0
FIELD_STATCAST_SCALE = 90 * FIELD_SQRT_2 / 51.0
FIELD_DIAMOND_SIZE = 201.5
FIELD_OUTFIELD_RADIUS = FIELD_SCREEN_H - (FIELD_DIAMOND_SIZE / 2)
FIELD_STRAIGHT_SIDE_LENGTH = sqrt(FIELD_SCREEN_H * (FIELD_SCREEN_H - FIELD_DIAMOND_SIZE))
FIELD_OFFSET = 440.0
FIELD_SCREEN_SCALE = FIELD_DIAMOND_SIZE / FIELD_ACTUAL_DIAMOND_SIZE_FT
FIELD_TOTAL_SCALE = FIELD_STATCAST_SCALE * FIELD_SCREEN_SCALE
FIELD_BASE_SIZE = 20

# Shared badge styling for field badges.
FIELD_BADGE_BORDER_RADIUS = 2
FIELD_MOUND_BADGE_FONT_SIZE = 16
FIELD_MOUND_BADGE_PAD_X = 4
FIELD_RUNNER_BADGE_FONT_SIZE = 16
FIELD_RUNNER_BADGE_PAD_X = 4
FIELD_DEFENDER_BADGE_FONT_SIZE = 16
FIELD_DEFENDER_BADGE_PAD_X = 4
FIELD_DEFENDER_SHIFT_UP_LEFT_PX = 14

# Middle infield and outfield placement tuning.
FIELD_MIDDLE_INFIELD_RADIUS_RATIO = 1.00
FIELD_SECOND_BASEMAN_ANGLE_FROM_FIRST_BASELINE_DEG = 25.0
FIELD_SHORTSTOP_ANGLE_FROM_FIRST_BASELINE_DEG = 65.0
FIELD_OUTFIELD_EDGE_MARGIN_PX = 14
FIELD_LEFT_FIELDER_ANGLE_FROM_3B_HOME_BASELINE_DEG = 20.0
FIELD_CENTER_FIELDER_ANGLE_FROM_3B_HOME_BASELINE_DEG = 45.0
FIELD_RIGHT_FIELDER_ANGLE_FROM_3B_HOME_BASELINE_DEG = 70.0

# Hit-line and animation styling.
FIELD_HIT_LINE_COLOR: tuple[int, int, int] = (255, 230, 80)
FIELD_HIT_LINE_WIDTH = 6
FIELD_PICKOFF_DASH_LENGTH = 14
FIELD_PICKOFF_GAP_LENGTH = 8
FIELD_HIT_BALL_RADIUS = 8
FIELD_HIT_BALL_COLOR: tuple[int, int, int] = FIELD_HIT_LINE_COLOR
FIELD_ANIM_BASE_MOVE_MS = 800
FIELD_ANIM_PAUSE_MS = 700
FIELD_ANIM_SEGMENT_COLOR: tuple[int, int, int] = (130, 50, 200)
FIELD_ANIM_SEGMENT_WIDTH = 10
FIELD_OUT_MARK_COLOR: tuple[int, int, int] = (220, 40, 40)
FIELD_OUT_MARK_WIDTH = 4
FIELD_OUT_MARK_HALF_LEN = 9.0
FIELD_STRIKEOUT_K_COLOR: tuple[int, int, int] = (220, 40, 40)
FIELD_STRIKEOUT_K_FLASH_MS = 300
FIELD_STRIKEOUT_K_FONT_SIZE = 160
FIELD_HIT_SCALE = FIELD_DIAMOND_SIZE * FIELD_SQRT_2 / 250.0

# Field drawing colors and sizes previously kept as inline literals.
FIELD_BASE_OUTLINE_COLOR: tuple[int, int, int] = (255, 255, 255)
FIELD_BASE_OUTLINE_WIDTH = 4
FIELD_MASK_CLEAR_COLOR: tuple[int, int, int, int] = (255, 255, 255, 0)
FIELD_MASK_OPAQUE_COLOR: tuple[int, int, int, int] = (255, 255, 255, 255)
FIELD_OVERLAY_CLEAR_COLOR: tuple[int, int, int, int] = (0, 0, 0, 0)
FIELD_BADGE_ROTATION_DEGREES = 45
FIELD_STRIKEOUT_ROTATION_DEGREES = 45
FIELD_STRIKEOUT_TEXT = "K"
FIELD_HIT_COORDINATE_X_OFFSET = 125.0
FIELD_HIT_COORDINATE_Y_OFFSET = 199.0
FIELD_ZERO_WIDTH = 0

# Pitcher mound and base centers.
FIELD_MOUND_LEFT = int(FIELD_OFFSET - FIELD_DIAMOND_SIZE / 2)
FIELD_MOUND_TOP = int(FIELD_SCREEN_H - FIELD_DIAMOND_SIZE / 2)
FIELD_HOME_PLATE_CENTER = (
    int(FIELD_OFFSET - FIELD_BASE_SIZE / 2),
    int(FIELD_SCREEN_H - FIELD_BASE_SIZE / 2),
)
FIELD_FIRST_BASE_CENTER = (
    int(FIELD_OFFSET - FIELD_BASE_SIZE / 2),
    int(FIELD_SCREEN_H - FIELD_DIAMOND_SIZE + FIELD_BASE_SIZE / 2),
)
FIELD_SECOND_BASE_CENTER = (
    int(FIELD_OFFSET - FIELD_DIAMOND_SIZE + FIELD_BASE_SIZE / 2),
    int(FIELD_SCREEN_H - FIELD_DIAMOND_SIZE + FIELD_BASE_SIZE / 2),
)
FIELD_THIRD_BASE_CENTER = (
    int(FIELD_OFFSET - FIELD_DIAMOND_SIZE + FIELD_BASE_SIZE / 2),
    int(FIELD_SCREEN_H - FIELD_BASE_SIZE / 2),
)
FIELD_BASE_CENTERS: dict[str, tuple[int, int]] = {
    "home": FIELD_HOME_PLATE_CENTER,
    "1b": FIELD_FIRST_BASE_CENTER,
    "2b": FIELD_SECOND_BASE_CENTER,
    "3b": FIELD_THIRD_BASE_CENTER,
}

# Exit point used for scoring animations: runner continues past home plate in the
# 3b→home direction (+x) until they disappear off the right edge of the field mask.
FIELD_HOME_SCORE_EXIT_OVERSHOOT_PX = 60
FIELD_HOME_SCORE_EXIT_POINT: tuple[int, int] = (
    FIELD_HOME_PLATE_CENTER[0] + FIELD_HOME_SCORE_EXIT_OVERSHOOT_PX,
    FIELD_HOME_PLATE_CENTER[1],
)

# Basepath ordering for runner animations.
FIELD_NEXT_BASE_FOR_PATH: dict[str, str | None] = {
    "home": "1b",
    "1b": "2b",
    "2b": "3b",
    "3b": "home",
}
FIELD_BASE_ORDER_RING = ["home", "1b", "2b", "3b"]

# Derived middle-infield anchors.
def _compute_field_middle_infield_anchors() -> tuple[tuple[int, int], tuple[int, int]]:
    home_x, home_y = FIELD_HOME_PLATE_CENTER
    first_dx = FIELD_FIRST_BASE_CENTER[0] - home_x
    first_dy = FIELD_FIRST_BASE_CENTER[1] - home_y
    second_dx = FIELD_SECOND_BASE_CENTER[0] - home_x
    second_dy = FIELD_SECOND_BASE_CENTER[1] - home_y
    first_baseline_angle = atan2(first_dy, first_dx)
    home_to_second = sqrt(second_dx * second_dx + second_dy * second_dy)
    radius = home_to_second * FIELD_MIDDLE_INFIELD_RADIUS_RATIO
    second_base_angle = first_baseline_angle - radians(
        FIELD_SECOND_BASEMAN_ANGLE_FROM_FIRST_BASELINE_DEG
    )
    shortstop_angle = first_baseline_angle - radians(
        FIELD_SHORTSTOP_ANGLE_FROM_FIRST_BASELINE_DEG
    )
    second_base_anchor = (
        int(round(home_x + radius * cos(second_base_angle))),
        int(round(home_y + radius * sin(second_base_angle))),
    )
    shortstop_anchor = (
        int(round(home_x + radius * cos(shortstop_angle))),
        int(round(home_y + radius * sin(shortstop_angle))),
    )
    return second_base_anchor, shortstop_anchor


FIELD_MIDDLE_INFIELD_2B_ANCHOR, FIELD_MIDDLE_INFIELD_SS_ANCHOR = (
    _compute_field_middle_infield_anchors()
)


def _field_outfield_direction_from_3b_home_baseline(
    angle_deg: float,
) -> tuple[float, float]:
    theta = radians(angle_deg)
    return (-cos(theta), -sin(theta))


def _field_max_radius_to_outfield_edge(angle_deg: float) -> float:
    hx, hy = FIELD_HOME_PLATE_CENTER
    cx, cy = FIELD_MOUND_LEFT, FIELD_MOUND_TOP
    vx, vy = _field_outfield_direction_from_3b_home_baseline(angle_deg)
    dx = hx - cx
    dy = hy - cy
    b = 2.0 * (vx * dx + vy * dy)
    c = dx * dx + dy * dy - float(FIELD_OUTFIELD_RADIUS) * float(FIELD_OUTFIELD_RADIUS)
    disc = b * b - 4.0 * c
    if disc <= 0.0:
        return 0.0
    sqrt_disc = sqrt(disc)
    t1 = (-b - sqrt_disc) / 2.0
    t2 = (-b + sqrt_disc) / 2.0
    candidates = [t for t in (t1, t2) if t > 0.0]
    return max(candidates) if candidates else 0.0


def _compute_field_outfield_anchor(angle_deg: float) -> tuple[int, int]:
    hx, hy = FIELD_HOME_PLATE_CENTER
    vx, vy = _field_outfield_direction_from_3b_home_baseline(angle_deg)
    radius = max(
        0.0,
        _field_max_radius_to_outfield_edge(angle_deg) - FIELD_OUTFIELD_EDGE_MARGIN_PX,
    )
    return (int(round(hx + vx * radius)), int(round(hy + vy * radius)))


FIELD_LEFT_FIELD_ANCHOR = _compute_field_outfield_anchor(
    FIELD_LEFT_FIELDER_ANGLE_FROM_3B_HOME_BASELINE_DEG
)
FIELD_CENTER_FIELD_ANCHOR = _compute_field_outfield_anchor(
    FIELD_CENTER_FIELDER_ANGLE_FROM_3B_HOME_BASELINE_DEG
)
FIELD_RIGHT_FIELD_ANCHOR = _compute_field_outfield_anchor(
    FIELD_RIGHT_FIELDER_ANGLE_FROM_3B_HOME_BASELINE_DEG
)

# Slot anchor lookups used by defender badge rendering.
FIELD_INFIELD_SLOT_ANCHORS: dict[str, tuple[int, int]] = {
    "1b": FIELD_FIRST_BASE_CENTER,
    "2b": FIELD_MIDDLE_INFIELD_2B_ANCHOR,
    "3b": FIELD_THIRD_BASE_CENTER,
    "ss": FIELD_MIDDLE_INFIELD_SS_ANCHOR,
}
FIELD_OUTFIELD_SLOT_ANCHORS: dict[str, tuple[int, int]] = {
    "lf": FIELD_LEFT_FIELD_ANCHOR,
    "cf": FIELD_CENTER_FIELD_ANCHOR,
    "rf": FIELD_RIGHT_FIELD_ANCHOR,
}

### Pitch Display ###

# Shared display roots aliased for pitch display-only consumption.
PITCH_DISPLAY_COLOR_BG = COLOR_BG
PITCH_DISPLAY_PITCH_PANEL_W = PITCH_PANEL_W
PITCH_DISPLAY_PITCHER_AREA_H = PITCHER_AREA_H

# Layout.
PITCH_DISPLAY_SPEED_AREA_H = 50
PITCH_DISPLAY_ZONE_AREA_H = PITCH_DISPLAY_PITCHER_AREA_H - PITCH_DISPLAY_SPEED_AREA_H

# Strike-zone coordinate mapping.
PITCH_DISPLAY_ZONE_X_MIN = -0.71
PITCH_DISPLAY_ZONE_X_MAX = 0.71
PITCH_DISPLAY_ZONE_Y_MIN = 1.5
PITCH_DISPLAY_ZONE_Y_MAX = 3.5
PITCH_DISPLAY_OUTER_PAD = 0.5

# Zone diagram spacing and markers.
PITCH_DISPLAY_INNER_PAD = 6
PITCH_DISPLAY_DOT_RADIUS = 3
PITCH_DISPLAY_HALO_RADIUS = 6
PITCH_DISPLAY_AUTO_BALL_POS: tuple[float, float] = (1.0, 1.0)

# Colors.
PITCH_DISPLAY_COLOR_ZONE_BG: tuple[int, int, int] = (10, 10, 10)
PITCH_DISPLAY_COLOR_ZONE_RECT: tuple[int, int, int] = (80, 80, 80)
PITCH_DISPLAY_COLOR_DIVIDER: tuple[int, int, int] = (60, 60, 60)
PITCH_DISPLAY_COLOR_BALL_DOT: tuple[int, int, int] = (25, 170, 50)
PITCH_DISPLAY_COLOR_STRIKE_DOT: tuple[int, int, int] = (200, 50, 50)
PITCH_DISPLAY_COLOR_IN_PLAY_DOT: tuple[int, int, int] = (80, 120, 200)
PITCH_DISPLAY_COLOR_HALO: tuple[int, int, int] = (255, 220, 0)
PITCH_DISPLAY_COLOR_SPEED: tuple[int, int, int] = (240, 240, 240)
PITCH_DISPLAY_COLOR_MPH: tuple[int, int, int] = (120, 120, 120)
PITCH_DISPLAY_CATEGORY_DOT_COLORS: dict[str, tuple[int, int, int]] = {
    "ball": PITCH_DISPLAY_COLOR_BALL_DOT,
    "strike": PITCH_DISPLAY_COLOR_STRIKE_DOT,
    "in_play": PITCH_DISPLAY_COLOR_IN_PLAY_DOT,
}

# Typography.
PITCH_DISPLAY_SPEED_FONT_SIZE = 28
PITCH_DISPLAY_MPH_FONT_SIZE = 14
PITCH_DISPLAY_MPH_TEXT = "MPH"
PITCH_DISPLAY_EMPTY_SPEED_TEXT = "—"

### PA Events ###

# Shared display roots aliased for plate appearance events consumption.
PA_EVENTS_COLOR_BG = COLOR_BG
PA_EVENTS_COLOR_TEXT = COLOR_TEXT
PA_EVENTS_PA_EVENTS_W = PA_EVENTS_W
PA_EVENTS_PITCHER_AREA_H = PITCHER_AREA_H
PA_EVENTS_PITCH_PANEL_W = PITCH_PANEL_W

# Layout and animation timing.
PA_EVENTS_AREA_W = PA_EVENTS_W
PA_EVENTS_AREA_H = PITCHER_AREA_H
PA_EVENTS_FONT_SIZE = 14
PA_EVENTS_PAD = 4
PA_EVENTS_GAP = 3
PA_EVENTS_SCROLL_SPEED = 20.0
PA_EVENTS_PAUSE_SECS = 1.5
PA_EVENTS_MAX_DT = 0.1

# Category colors.
PA_EVENTS_COLOR_BALL: tuple[int, int, int] = (25, 90, 30)
PA_EVENTS_COLOR_STRIKE: tuple[int, int, int] = (90, 80, 15)
PA_EVENTS_COLOR_IN_PLAY: tuple[int, int, int] = (50, 50, 70)
PA_EVENTS_COLOR_RUN: tuple[int, int, int] = (110, 30, 25)
PA_EVENTS_COLOR_ADVANCE: tuple[int, int, int] = (35, 55, 95)
PA_EVENTS_COLOR_SUB: tuple[int, int, int] = (55, 40, 80)
PA_EVENTS_COLOR_SWITCH: tuple[int, int, int] = (35, 55, 80)
PA_EVENTS_COLOR_PICKOFF: tuple[int, int, int] = (80, 50, 20)
PA_EVENTS_CATEGORY_COLORS: dict[str, tuple[int, int, int]] = {
    "ball": PA_EVENTS_COLOR_BALL,
    "strike": PA_EVENTS_COLOR_STRIKE,
    "in_play": PA_EVENTS_COLOR_IN_PLAY,
    "run": PA_EVENTS_COLOR_RUN,
    "advance": PA_EVENTS_COLOR_ADVANCE,
    "sub": PA_EVENTS_COLOR_SUB,
    "switch": PA_EVENTS_COLOR_SWITCH,
    "pickoff": PA_EVENTS_COLOR_PICKOFF,
}

### Scoreboard ###

# Scoreboard typography and sizing.
# Note: SCOREBOARD_BSO_PANEL_W and SCOREBOARD_H are in the shared layout roots above
# since they are consumed by PITCH_DISPLAY and PA_EVENTS sections as well.
SCOREBOARD_FONT_SIZE = 18
SCOREBOARD_SCORE_FONT_SIZE = 32
SCOREBOARD_HEADER_HEIGHT = 28  # matches the 28 in SCOREBOARD_H above
SCOREBOARD_TEAM_COL_W = 60    # matches the 60 in SCOREBOARD_H above
SCOREBOARD_RHE_COL_W = 36
SCOREBOARD_ACTIVE_BORDER_W = 3

# Shared display roots aliased for scoreboard-only consumption.
SCOREBOARD_COLOR_BG = COLOR_BG
SCOREBOARD_COLOR_TEXT = COLOR_TEXT
SCOREBOARD_COLOR_DIVIDER = COLOR_DIVIDER
SCOREBOARD_SCREEN_W = SCREEN_W
SCOREBOARD_SCREEN_H = SCREEN_H

# Scoreboard-only display values.
SCOREBOARD_LOGO_PAD = 5
SCOREBOARD_COLOR_LOGO_BG: tuple[int, int, int] = (255, 255, 255)
SCOREBOARD_LOADING_TEXT = "Loading..."
SCOREBOARD_EMPTY_INNING_TEXT = "·"
SCOREBOARD_TOTAL_LABELS: tuple[str, str, str] = ("R", "H", "E")

### Batting Order ###

# Lineup panel and pitcher panel typography and sizing.
LINEUP_PANEL_W = SCREEN_W // 3
LINEUP_FONT_SIZE = 18
LINEUP_NAME_MAX_CHARS = 10
LINEUP_ROW_H = SCREEN_H // 9
BATTER_NAME_FONT_SIZE = 24
BATTER_STATS_FONT_SIZE = 18
PITCHER_NAME_FONT_SIZE = 24
PITCHER_STATS_FONT_SIZE = 16
PITCHER_NAME_X = 120
PITCHER_STATS_Y = 60

# Shared display roots aliased for batting-order-only consumption.
BATTING_ORDER_COLOR_BG = COLOR_BG
BATTING_ORDER_COLOR_TEXT = COLOR_TEXT
BATTING_ORDER_COLOR_DIVIDER = COLOR_DIVIDER
BATTING_ORDER_COLOR_LINEUP_ACTIVE_BG = COLOR_LINEUP_ACTIVE_BG
BATTING_ORDER_COLOR_SCOREBOARD_DIMMED = COLOR_SCOREBOARD_DIMMED
BATTING_ORDER_COLOR_NUMBER_BADGE_AWAY_BG = COLOR_NUMBER_BADGE_AWAY_BG
BATTING_ORDER_COLOR_NUMBER_BADGE_HOME_BG = COLOR_NUMBER_BADGE_HOME_BG
BATTING_ORDER_COLOR_NUMBER_BADGE_FG = COLOR_NUMBER_BADGE_FG
BATTING_ORDER_SCREEN_W = SCREEN_W
BATTING_ORDER_SCREEN_H = SCREEN_H
BATTING_ORDER_LINEUP_PANEL_W = LINEUP_PANEL_W
BATTING_ORDER_LINEUP_FONT_SIZE = LINEUP_FONT_SIZE
BATTING_ORDER_LINEUP_ROW_H = LINEUP_ROW_H
BATTING_ORDER_BATTER_NAME_FONT_SIZE = BATTER_NAME_FONT_SIZE

# Batting-order-only display values.
BATTING_ORDER_ACTIVE_FG: tuple[int, int, int] = (255, 220, 0)
BATTING_ORDER_INDICATOR_COLOR: tuple[int, int, int] = (140, 140, 200)
BATTING_ORDER_LOGO_SIZE = 36
BATTING_ORDER_LOGO_WHITE_PAD = 2
BATTING_ORDER_RIGHT_PAD = 12
BATTING_ORDER_RIGHT_W = BATTING_ORDER_SCREEN_W - BATTING_ORDER_LINEUP_PANEL_W
BATTING_ORDER_HALF_H = BATTING_ORDER_SCREEN_H // 2
BATTING_ORDER_STATS_FONT_SIZE = 14
BATTING_ORDER_STATS_ALTERNATE_SECS = 5
BATTING_ORDER_BADGE_PAD_X = 4
BATTING_ORDER_BADGE_GAP = 5
BATTING_ORDER_LABEL_VALUE_GAP = 2
BATTING_ORDER_GRID_ROW_GAP = 6
BATTING_ORDER_SECTION_TOP_PAD = 8
BATTING_ORDER_PANEL_TEXT_PAD = 6
BATTING_ORDER_LOGO_TEXT_GAP = 8
BATTING_ORDER_BADGE_TEXT_GAP = 8
BATTING_ORDER_NAME_TRUNCATION_PAD = 5
BATTING_ORDER_INDICATOR_MARGIN = 4
BATTING_ORDER_PC_ST_W = 100
BATTING_ORDER_LOADING_TEXT = "Loading..."
BATTING_ORDER_LOADING_STATS_TEXT = "Loading stats..."
BATTING_ORDER_NO_BATTER_TEXT = "No batter data"
BATTING_ORDER_NO_PITCHER_TEXT = "No pitcher data"
BATTING_ORDER_CAREER_LABEL = "CAREER"
BATTING_ORDER_SEASON_LABEL = "SEASON"
BATTING_ORDER_NAME_ELLIPSIS = "…"
BATTING_ORDER_LOGO_TILE_BG: tuple[int, int, int] = (255, 255, 255)

### Clock Display ###

# Clock display typography and sizing.
CLOCK_DISPLAY_FONT_SIZE = 32
CLOCK_DISPLAY_PAD = 4
CLOCK_DISPLAY_H = 48

CLOCK_DISPLAY_COLOR_BG = COLOR_BG
CLOCK_DISPLAY_COLOR_TEXT = COLOR_TEXT
CLOCK_DISPLAY_SCREEN_W = SCREEN_W
CLOCK_DISPLAY_SCOREBOARD_BSO_PANEL_W = SCOREBOARD_BSO_PANEL_W

### Count Display ###

COUNT_DISPLAY_COLOR_TEXT = COLOR_TEXT
COUNT_DISPLAY_SCREEN_W = SCREEN_W
COUNT_DISPLAY_SCOREBOARD_BSO_PANEL_W = SCOREBOARD_BSO_PANEL_W
COUNT_DISPLAY_CLOCK_DISPLAY_H = CLOCK_DISPLAY_H
COUNT_DISPLAY_PITCHER_AREA_H = PITCHER_AREA_H
COUNT_DISPLAY_COLOR_SCOREBOARD_AWAY_BG = COLOR_SCOREBOARD_AWAY_BG
COUNT_DISPLAY_COLOR_SCOREBOARD_HEADER_BG = COLOR_SCOREBOARD_HEADER_BG
COUNT_DISPLAY_COLOR_SCOREBOARD_HOME_BG = COLOR_SCOREBOARD_HOME_BG
COUNT_DISPLAY_COLOR_BALL: tuple[int, int, int] = (50, 180, 50)
COUNT_DISPLAY_COLOR_STRIKE: tuple[int, int, int] = (220, 200, 50)
COUNT_DISPLAY_COLOR_OUT: tuple[int, int, int] = (200, 60, 60)
COUNT_DISPLAY_COLOR_EMPTY: tuple[int, int, int] = (70, 70, 70)
COUNT_DISPLAY_DOT_RADIUS = 10
COUNT_DISPLAY_DOT_SPACING = 22
COUNT_DISPLAY_LETTER_AREA_W = 20
COUNT_DISPLAY_RIGHT_PAD = 10
COUNT_DISPLAY_BSO_FONT_SIZE = 21
COUNT_DISPLAY_SECTIONS: tuple[tuple[str, tuple[int, int, int], int], ...] = (
    ("B", COUNT_DISPLAY_COLOR_BALL, 4),
    ("S", COUNT_DISPLAY_COLOR_STRIKE, 3),
    ("O", COUNT_DISPLAY_COLOR_OUT, 3),
)
COUNT_DISPLAY_BG_COLORS: tuple[tuple[int, int, int], ...] = (
    COUNT_DISPLAY_COLOR_SCOREBOARD_AWAY_BG,
    COUNT_DISPLAY_COLOR_SCOREBOARD_HEADER_BG,
    COUNT_DISPLAY_COLOR_SCOREBOARD_HOME_BG,
)

### Game Countdown ###

GAME_COUNTDOWN_COLOR_BG = COLOR_BG
GAME_COUNTDOWN_COLOR_TEXT = COLOR_TEXT
GAME_COUNTDOWN_SCREEN_W = SCREEN_W
GAME_COUNTDOWN_SCREEN_H = SCREEN_H
GAME_COUNTDOWN_LABEL_FONT_SIZE = 18
GAME_COUNTDOWN_COUNTDOWN_FONT_SIZE = 52
GAME_COUNTDOWN_LINE_GAP = 16
GAME_COUNTDOWN_COLOR_LABEL: tuple[int, int, int] = (120, 120, 120)
GAME_COUNTDOWN_STARTING_NOW_TEXT = "STARTING NOW"
GAME_COUNTDOWN_LABEL_TEXT = "GAME STARTS IN"

### Blank Screen ###

BLANK_SCREEN_COLOR_BG = COLOR_BG

### Main Menu ###

MAIN_MENU_COLOR_BG = COLOR_BG
MAIN_MENU_COLOR_TEXT = COLOR_TEXT
MAIN_MENU_COLOR_ROW_EVEN = COLOR_ROW_EVEN
MAIN_MENU_COLOR_ROW_ODD = COLOR_ROW_ODD
MAIN_MENU_COLOR_ROW_HOVER = COLOR_ROW_HOVER
MAIN_MENU_SCREEN_W = SCREEN_W
MAIN_MENU_MENU_ROW_HEIGHT = MENU_ROW_HEIGHT
MAIN_MENU_MENU_FONT_SIZE = MENU_FONT_SIZE
MAIN_MENU_ITEMS_LIST = MAIN_MENU_ITEMS
MAIN_MENU_TEXT_PAD_X = 8

### Game Select ###

GAME_SELECT_COLOR_BG = COLOR_BG
GAME_SELECT_COLOR_TEXT = COLOR_TEXT
GAME_SELECT_COLOR_TAB_ACTIVE = COLOR_TAB_ACTIVE
GAME_SELECT_COLOR_TAB_INACTIVE = COLOR_TAB_INACTIVE
GAME_SELECT_COLOR_ROW_EVEN = COLOR_ROW_EVEN
GAME_SELECT_COLOR_ROW_ODD = COLOR_ROW_ODD
GAME_SELECT_COLOR_ROW_HOVER = COLOR_ROW_HOVER
GAME_SELECT_SCREEN_W = SCREEN_W
GAME_SELECT_SCREEN_H = SCREEN_H
GAME_SELECT_MENU_TAB_HEIGHT = MENU_TAB_HEIGHT
GAME_SELECT_MENU_ROW_HEIGHT = MENU_ROW_HEIGHT
GAME_SELECT_MENU_FONT_SIZE = MENU_FONT_SIZE
GAME_SELECT_TABS = TABS
GAME_SELECT_TEXT_PAD_X = 8
GAME_SELECT_RIGHT_TEXT_PAD_X = 8
GAME_SELECT_SCORE_GAP_X = 24
GAME_SELECT_SCORE_PAD_TEXT = "   "
GAME_SELECT_GAME_LABEL_PREFIX = "GAME"

### Settings Menu ###

SETTINGS_MENU_COLOR_BG = COLOR_BG
SETTINGS_MENU_COLOR_TEXT = COLOR_TEXT
SETTINGS_MENU_COLOR_TAB_ACTIVE = COLOR_TAB_ACTIVE
SETTINGS_MENU_COLOR_ROW_EVEN = COLOR_ROW_EVEN
SETTINGS_MENU_COLOR_ROW_ODD = COLOR_ROW_ODD
SETTINGS_MENU_COLOR_ROW_HOVER = COLOR_ROW_HOVER
SETTINGS_MENU_SCREEN_W = SCREEN_W
SETTINGS_MENU_MENU_TAB_HEIGHT = MENU_TAB_HEIGHT
SETTINGS_MENU_MENU_ROW_HEIGHT = MENU_ROW_HEIGHT
SETTINGS_MENU_MENU_FONT_SIZE = MENU_FONT_SIZE
SETTINGS_MENU_ROWS: list[str] = ["Refresh Rate"]
SETTINGS_MENU_REFRESH_RATE_OPTIONS: list[int] = [1, 5, 10, 15, 30, 60]
SETTINGS_MENU_HEADER_TEXT = "SETTINGS"
SETTINGS_MENU_TEXT_PAD_X = 8
SETTINGS_MENU_LEFT_ARROW = "◄"
SETTINGS_MENU_RIGHT_ARROW = "►"
SETTINGS_MENU_SECONDS_SUFFIX = "s"

### Game Preview ###

GAME_PREVIEW_COLOR_BG = COLOR_BG
GAME_PREVIEW_COLOR_TEXT = COLOR_TEXT
GAME_PREVIEW_SCREEN_W = SCREEN_W
GAME_PREVIEW_SCREEN_H = SCREEN_H
GAME_PREVIEW_TEAM_FONT_SIZE = 29
GAME_PREVIEW_AT_FONT_SIZE = 23
GAME_PREVIEW_META_FONT_SIZE = 21
GAME_PREVIEW_PAD = 16
GAME_PREVIEW_LOGO_TOP_PAD = 8
GAME_PREVIEW_LOGO_WHITE_PAD = 5
GAME_PREVIEW_LOGO_GAP = 10
GAME_PREVIEW_DIVIDER_GAP = 12
GAME_PREVIEW_LINE_GAP = 8
GAME_PREVIEW_DIVIDER_COLOR: tuple[int, int, int] = (80, 80, 80)
GAME_PREVIEW_AT_TEXT = "at"
GAME_PREVIEW_AT_COLOR: tuple[int, int, int] = (160, 160, 160)
GAME_PREVIEW_DATETIME_SEPARATOR = "  -  "
GAME_PREVIEW_LOGO_TILE_BG: tuple[int, int, int] = (255, 255, 255)

### Player Select ###

PLAYER_SELECT_COLOR_BG = COLOR_BG
PLAYER_SELECT_COLOR_TEXT = COLOR_TEXT
PLAYER_SELECT_COLOR_DIVIDER = COLOR_DIVIDER
PLAYER_SELECT_COLOR_ROW_EVEN = COLOR_ROW_EVEN
PLAYER_SELECT_COLOR_ROW_ODD = COLOR_ROW_ODD
PLAYER_SELECT_COLOR_ROW_HOVER = COLOR_ROW_HOVER
PLAYER_SELECT_COLOR_SCOREBOARD_DIMMED = COLOR_SCOREBOARD_DIMMED
PLAYER_SELECT_SCREEN_W = SCREEN_W
PLAYER_SELECT_SCREEN_H = SCREEN_H
PLAYER_SELECT_MENU_ROW_HEIGHT = MENU_ROW_HEIGHT
PLAYER_SELECT_MENU_FONT_SIZE = MENU_FONT_SIZE
PLAYER_SELECT_PANEL_W = SCREEN_W // 2
PLAYER_SELECT_ROW_H = MENU_ROW_HEIGHT
PLAYER_SELECT_ROWS_VISIBLE = SCREEN_H // PLAYER_SELECT_ROW_H
PLAYER_SELECT_LOGO_SMALL = 20
PLAYER_SELECT_LOGO_CARD = 28
PLAYER_SELECT_NUMBER_BADGE_BG: tuple[int, int, int] = (200, 200, 200)
PLAYER_SELECT_NUMBER_BADGE_FG: tuple[int, int, int] = (0, 0, 0)
PLAYER_SELECT_NUMBER_BADGE_PAD_X = 3
PLAYER_SELECT_NUMBER_BADGE_GAP = 4
PLAYER_SELECT_BADGE_BORDER_RADIUS = 2
PLAYER_SELECT_EDGE_PAD = 4
PLAYER_SELECT_SECTION_PAD = 6
PLAYER_SELECT_ELLIPSIS = "…"
PLAYER_SELECT_LOADING_TEXT = "Loading..."
PLAYER_SELECT_RIGHT_PANEL_TEXT_PAD = 8
PLAYER_SELECT_PHOTO_MARGIN = 10
PLAYER_SELECT_PHOTO_BOTTOM_PAD = 5

### Player Stats Panel ###

PLAYER_STATS_PANEL_COLOR_BG = COLOR_BG
PLAYER_STATS_PANEL_COLOR_TEXT = COLOR_TEXT
PLAYER_STATS_PANEL_COLOR_ROW_EVEN = COLOR_ROW_EVEN
PLAYER_STATS_PANEL_COLOR_ROW_ODD = COLOR_ROW_ODD
PLAYER_STATS_PANEL_COLOR_SCOREBOARD_DIMMED = COLOR_SCOREBOARD_DIMMED
PLAYER_STATS_PANEL_SCREEN_W = SCREEN_W
PLAYER_STATS_PANEL_SCREEN_H = SCREEN_H
PLAYER_STATS_PANEL_MENU_FONT_SIZE = MENU_FONT_SIZE
PLAYER_STATS_PANEL_ROW_H = 24
PLAYER_STATS_PANEL_ROW_PAD = 3
PLAYER_STATS_PANEL_ROWS_VISIBLE = SCREEN_H // PLAYER_STATS_PANEL_ROW_H
PLAYER_STATS_PANEL_SCROLL_PX_PER_SEC = PLAYER_STATS_PANEL_ROW_H / 2.0
PLAYER_STATS_PANEL_BROWSE_COOLOFF = 0.5
PLAYER_STATS_PANEL_EDGE_PAD = 8
PLAYER_STATS_PANEL_NO_PLAYER_TEXT = "No player selected"
PLAYER_STATS_PANEL_LOADING_TEXT = "Loading..."
PLAYER_STATS_PANEL_NO_DATA_TEXT = "No data"
PLAYER_STATS_PANEL_EMPTY_VALUE_TEXT = "-"

### Base Components ###

BASE_COMPONENT_COLOR_BG = COLOR_BG
BASE_COMPONENT_SCREEN_W = SCREEN_W
BASE_COMPONENT_SCREEN_H = SCREEN_H

### Screens ###

SCREENS_LEFT_JUMBOTRON_POS = LEFT_JUMBOTRON_POS
SCREENS_RIGHT_JUMBOTRON_POS = RIGHT_JUMBOTRON_POS
SCREENS_DIAMOND_POS = DIAMOND_POS

### App ###

APP_FULL_SCREEN_W = FULL_SCREEN_W
APP_FULL_SCREEN_H = FULL_SCREEN_H
APP_WINDOW_TITLE = "Baseball"
