# generated by datamodel-codegen:
#   filename:  live_game.json
#   timestamp: 2026-05-07T13:14:24+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel


class MetaData(BaseModel):
    wait: int | None = None
    timeStamp: str | None = None
    gameEvents: list[str] | None = None
    logicalEvents: list[str] | None = None


class Game(BaseModel):
    pk: int | None = None
    type: str | None = None
    doubleHeader: str | None = None
    id: str | None = None
    gamedayType: str | None = None
    tiebreaker: str | None = None
    gameNumber: int | None = None
    calendarEventID: str | None = None
    season: str | None = None
    seasonDisplay: str | None = None


class Datetime(BaseModel):
    dateTime: str | None = None
    originalDate: str | None = None
    officialDate: str | None = None
    dayNight: str | None = None
    time: str | None = None
    ampm: str | None = None


class GameState(BaseModel):
    abstractGameState: str | None = None
    codedGameState: str | None = None
    detailedState: str | None = None
    statusCode: str | None = None
    startTimeTBD: bool | None = None
    abstractGameCode: str | None = None


class PrimaryPosition(BaseModel):
    code: str | None = None
    name: str | None = None
    type: str | None = None
    abbreviation: str | None = None


class BatSide(BaseModel):
    code: str | None = None
    description: str | None = None


class PitchHand(BatSide):
    pass


class GameDataPlayer(BaseModel):
    id: int | None = None
    fullName: str | None = None
    link: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    primaryNumber: str | None = None
    birthDate: str | None = None
    currentAge: int | None = None
    birthCity: str | None = None
    birthStateProvince: str | None = None
    birthCountry: str | None = None
    height: str | None = None
    weight: int | None = None
    active: bool | None = None
    primaryPosition: PrimaryPosition | None = None
    useName: str | None = None
    useLastName: str | None = None
    middleName: str | None = None
    boxscoreName: str | None = None
    gender: str | None = None
    isPlayer: bool | None = None
    isVerified: bool | None = None
    draftYear: int | None = None
    mlbDebutDate: str | None = None
    batSide: BatSide | None = None
    pitchHand: PitchHand | None = None
    nameFirstLast: str | None = None
    nameSlug: str | None = None
    firstLastName: str | None = None
    lastFirstName: str | None = None
    lastInitName: str | None = None
    initLastName: str | None = None
    fullFMLName: str | None = None
    fullLFMName: str | None = None
    strikeZoneTop: float | None = None
    strikeZoneBottom: float | None = None
    pronunciation: str | None = None
    nameMatrilineal: str | None = None
    nickName: str | None = None


class GameDataPlayersDict(RootModel[dict[str, GameDataPlayer] | None]):
    root: dict[str, GameDataPlayer] | None = Field(None, title="GameDataPlayersDict")


class DefaultCoordinates(BaseModel):
    latitude: float | None = None
    longitude: float | None = None


class Location(BaseModel):
    address1: str | None = None
    city: str | None = None
    state: str | None = None
    stateAbbrev: str | None = None
    postalCode: str | None = None
    defaultCoordinates: DefaultCoordinates | None = None
    azimuthAngle: float | None = None
    elevation: int | None = None
    country: str | None = None
    phone: str | None = None


class TimeZone(BaseModel):
    tz: str | None = None
    id: str | None = None
    offset: int | None = None
    offsetAtGameTime: int | None = None


class FieldInfo(BaseModel):
    capacity: int | None = None
    turfType: str | None = None
    roofType: str | None = None
    leftLine: int | None = None
    left: int | None = None
    leftCenter: int | None = None
    center: int | None = None
    rightCenter: int | None = None
    rightLine: int | None = None


class GameVenue(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None
    location: Location | None = None
    timeZone: TimeZone | None = None
    fieldInfo: FieldInfo | None = None
    active: bool | None = None
    season: str | None = None


class OfficialVenue(BaseModel):
    id: int | None = None
    link: str | None = None


class Weather(BaseModel):
    condition: str | None = None
    temp: str | None = None
    wind: str | None = None


class GameInfo(BaseModel):
    attendance: int | None = None
    firstPitch: str | None = None
    gameDurationMinutes: int | None = None


class Flags(BaseModel):
    noHitter: bool | None = None
    perfectGame: bool | None = None
    awayTeamNoHitter: bool | None = None
    awayTeamPerfectGame: bool | None = None
    homeTeamNoHitter: bool | None = None
    homeTeamPerfectGame: bool | None = None


class OfficialScorer(BaseModel):
    id: int | None = None
    fullName: str | None = None
    link: str | None = None


class PrimaryDatacaster(OfficialScorer):
    pass


class Pitcher(OfficialScorer):
    pass


class Batter(OfficialScorer):
    pass


class Catcher(OfficialScorer):
    pass


class First(OfficialScorer):
    pass


class Second(OfficialScorer):
    pass


class Third(OfficialScorer):
    pass


class Shortstop(OfficialScorer):
    pass


class Left(OfficialScorer):
    pass


class Center(OfficialScorer):
    pass


class Right(OfficialScorer):
    pass


class OnDeck(OfficialScorer):
    pass


class InHole(OfficialScorer):
    pass


class Official(OfficialScorer):
    pass


class OfficialAssignment(BaseModel):
    official: Official | None = None
    officialType: str | None = None


class BoxscoreInfoItem(BaseModel):
    label: str | None = None
    value: str | None = None


class TopPerformerPerson(BaseModel):
    id: int | None = None
    fullName: str | None = None
    link: str | None = None
    boxscoreName: str | None = None


class Position(PrimaryPosition):
    pass


class AllPosition(PrimaryPosition):
    pass


class Winner(OfficialScorer):
    pass


class Loser(OfficialScorer):
    pass


class Decisions(BaseModel):
    winner: Winner | None = None
    loser: Loser | None = None


class Leaders(BaseModel):
    hitDistance: dict[str, Any] | None = None
    hitSpeed: dict[str, Any] | None = None
    pitchSpeed: dict[str, Any] | None = None


class SpringLeague(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None
    abbreviation: str | None = None


class TeamVenue(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None


class SpringVenue(OfficialVenue):
    pass


class League(TeamVenue):
    pass


class Division(TeamVenue):
    pass


class Sport(BaseModel):
    id: int | None = None
    link: str | None = None
    name: str | None = None


class LeagueRecord(BaseModel):
    wins: int | None = None
    losses: int | None = None
    ties: int | None = None
    pct: str | None = None


class Record(BaseModel):
    gamesPlayed: int | None = None
    wildCardGamesBack: str | None = None
    leagueGamesBack: str | None = None
    springLeagueGamesBack: str | None = None
    sportGamesBack: str | None = None
    divisionGamesBack: str | None = None
    conferenceGamesBack: str | None = None
    leagueRecord: LeagueRecord | None = None
    records: dict[str, Any] | None = None
    divisionLeader: bool | None = None
    wins: int | None = None
    losses: int | None = None
    winningPercentage: str | None = None


class GameTeam(BaseModel):
    springLeague: SpringLeague | None = None
    allStarStatus: str | None = None
    id: int | None = None
    name: str | None = None
    link: str | None = None
    season: int | None = None
    venue: TeamVenue | None = Field(None, title="TeamVenue")
    springVenue: SpringVenue | None = None
    teamCode: str | None = None
    fileCode: str | None = None
    abbreviation: str | None = None
    teamName: str | None = None
    locationName: str | None = None
    firstYearOfPlay: str | None = None
    league: League | None = None
    division: Division | None = None
    sport: Sport | None = None
    shortName: str | None = None
    record: Record | None = None
    franchiseName: str | None = None
    clubName: str | None = None
    active: bool | None = None


class ReviewCounts(BaseModel):
    used: int | None = None
    remaining: int | None = None


class AbsChallengeCounts(BaseModel):
    usedSuccessful: int | None = None
    usedFailed: int | None = None
    remaining: int | None = None


class PersonRef(OfficialScorer):
    pass


class MoundVisitCounts(ReviewCounts):
    pass


class LinescoreInningHalf(BaseModel):
    runs: int | None = None
    hits: int | None = None
    errors: int | None = None
    leftOnBase: int | None = None


class TeamBattingStats(BaseModel):
    flyOuts: int | None = None
    groundOuts: int | None = None
    airOuts: int | None = None
    runs: int | None = None
    doubles: int | None = None
    triples: int | None = None
    homeRuns: int | None = None
    strikeOuts: int | None = None
    baseOnBalls: int | None = None
    intentionalWalks: int | None = None
    hits: int | None = None
    hitByPitch: int | None = None
    avg: str | None = None
    atBats: int | None = None
    obp: str | None = None
    slg: str | None = None
    ops: str | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    groundIntoDoublePlay: int | None = None
    groundIntoTriplePlay: int | None = None
    plateAppearances: int | None = None
    totalBases: int | None = None
    rbi: int | None = None
    leftOnBase: int | None = None
    sacBunts: int | None = None
    sacFlies: int | None = None
    catchersInterference: int | None = None
    pickoffs: int | None = None
    atBatsPerHomeRun: str | None = None
    popOuts: int | None = None
    lineOuts: int | None = None


class TeamPitchingStats(BaseModel):
    flyOuts: int | None = None
    groundOuts: int | None = None
    airOuts: int | None = None
    runs: int | None = None
    doubles: int | None = None
    triples: int | None = None
    homeRuns: int | None = None
    strikeOuts: int | None = None
    baseOnBalls: int | None = None
    intentionalWalks: int | None = None
    hits: int | None = None
    hitByPitch: int | None = None
    atBats: int | None = None
    obp: str | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    caughtStealingPercentage: str | None = None
    numberOfPitches: int | None = None
    era: str | None = None
    inningsPitched: str | None = None
    saveOpportunities: int | None = None
    earnedRuns: int | None = None
    whip: str | None = None
    battersFaced: int | None = None
    outs: int | None = None
    completeGames: int | None = None
    shutouts: int | None = None
    pitchesThrown: int | None = None
    balls: int | None = None
    strikes: int | None = None
    strikePercentage: str | None = None
    hitBatsmen: int | None = None
    balks: int | None = None
    wildPitches: int | None = None
    pickoffs: int | None = None
    groundOutsToAirouts: str | None = None
    rbi: int | None = None
    pitchesPerInning: str | None = None
    runsScoredPer9: str | None = None
    homeRunsPer9: str | None = None
    inheritedRunners: int | None = None
    inheritedRunnersScored: int | None = None
    catchersInterference: int | None = None
    sacBunts: int | None = None
    sacFlies: int | None = None
    passedBall: int | None = None
    popOuts: int | None = None
    lineOuts: int | None = None


class TeamFieldingStats(BaseModel):
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    caughtStealingPercentage: str | None = None
    assists: int | None = None
    putOuts: int | None = None
    errors: int | None = None
    chances: int | None = None
    passedBall: int | None = None
    pickoffs: int | None = None


class TeamStats(BaseModel):
    batting: TeamBattingStats | None = None
    pitching: TeamPitchingStats | None = None
    fielding: TeamFieldingStats | None = None


class PlayerBattingStats(BaseModel):
    summary: str | None = None
    gamesPlayed: int | None = None
    flyOuts: int | None = None
    groundOuts: int | None = None
    airOuts: int | None = None
    runs: int | None = None
    doubles: int | None = None
    triples: int | None = None
    homeRuns: int | None = None
    strikeOuts: int | None = None
    baseOnBalls: int | None = None
    intentionalWalks: int | None = None
    hits: int | None = None
    hitByPitch: int | None = None
    atBats: int | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    groundIntoDoublePlay: int | None = None
    groundIntoTriplePlay: int | None = None
    plateAppearances: int | None = None
    totalBases: int | None = None
    rbi: int | None = None
    leftOnBase: int | None = None
    sacBunts: int | None = None
    sacFlies: int | None = None
    catchersInterference: int | None = None
    pickoffs: int | None = None
    atBatsPerHomeRun: str | None = None
    popOuts: int | None = None
    lineOuts: int | None = None


class PlayerPitchingStats(BaseModel):
    summary: str | None = None
    gamesPlayed: int | None = None
    gamesStarted: int | None = None
    flyOuts: int | None = None
    groundOuts: int | None = None
    airOuts: int | None = None
    runs: int | None = None
    doubles: int | None = None
    triples: int | None = None
    homeRuns: int | None = None
    strikeOuts: int | None = None
    baseOnBalls: int | None = None
    intentionalWalks: int | None = None
    hits: int | None = None
    hitByPitch: int | None = None
    atBats: int | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    numberOfPitches: int | None = None
    inningsPitched: str | None = None
    wins: int | None = None
    losses: int | None = None
    saves: int | None = None
    saveOpportunities: int | None = None
    holds: int | None = None
    blownSaves: int | None = None
    earnedRuns: int | None = None
    battersFaced: int | None = None
    outs: int | None = None
    gamesPitched: int | None = None
    completeGames: int | None = None
    shutouts: int | None = None
    pitchesThrown: int | None = None
    balls: int | None = None
    strikes: int | None = None
    strikePercentage: str | None = None
    hitBatsmen: int | None = None
    balks: int | None = None
    wildPitches: int | None = None
    pickoffs: int | None = None
    rbi: int | None = None
    gamesFinished: int | None = None
    runsScoredPer9: str | None = None
    homeRunsPer9: str | None = None
    inheritedRunners: int | None = None
    inheritedRunnersScored: int | None = None
    catchersInterference: int | None = None
    sacBunts: int | None = None
    sacFlies: int | None = None
    passedBall: int | None = None
    popOuts: int | None = None
    lineOuts: int | None = None
    note: str | None = None


class PlayerFieldingStats(BaseModel):
    gamesStarted: int | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    caughtStealingPercentage: str | None = None
    assists: int | None = None
    putOuts: int | None = None
    errors: int | None = None
    chances: int | None = None
    fielding: str | None = None
    passedBall: int | None = None
    pickoffs: int | None = None


class PlayerStats(BaseModel):
    batting: PlayerBattingStats | None = None
    pitching: PlayerPitchingStats | None = None
    fielding: PlayerFieldingStats | None = None


class PlayerSeasonBattingStats(BaseModel):
    gamesPlayed: int | None = None
    flyOuts: int | None = None
    groundOuts: int | None = None
    airOuts: int | None = None
    runs: int | None = None
    doubles: int | None = None
    triples: int | None = None
    homeRuns: int | None = None
    strikeOuts: int | None = None
    baseOnBalls: int | None = None
    intentionalWalks: int | None = None
    hits: int | None = None
    hitByPitch: int | None = None
    avg: str | None = None
    atBats: int | None = None
    obp: str | None = None
    slg: str | None = None
    ops: str | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    caughtStealingPercentage: str | None = None
    groundIntoDoublePlay: int | None = None
    groundIntoTriplePlay: int | None = None
    plateAppearances: int | None = None
    totalBases: int | None = None
    rbi: int | None = None
    leftOnBase: int | None = None
    sacBunts: int | None = None
    sacFlies: int | None = None
    babip: str | None = None
    groundOutsToAirouts: str | None = None
    catchersInterference: int | None = None
    pickoffs: int | None = None
    atBatsPerHomeRun: str | None = None
    popOuts: int | None = None
    lineOuts: int | None = None


class PlayerSeasonPitchingStats(BaseModel):
    gamesPlayed: int | None = None
    gamesStarted: int | None = None
    flyOuts: int | None = None
    groundOuts: int | None = None
    airOuts: int | None = None
    runs: int | None = None
    doubles: int | None = None
    triples: int | None = None
    homeRuns: int | None = None
    strikeOuts: int | None = None
    baseOnBalls: int | None = None
    intentionalWalks: int | None = None
    hits: int | None = None
    hitByPitch: int | None = None
    atBats: int | None = None
    obp: str | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    caughtStealingPercentage: str | None = None
    numberOfPitches: int | None = None
    era: str | None = None
    inningsPitched: str | None = None
    wins: int | None = None
    losses: int | None = None
    saves: int | None = None
    saveOpportunities: int | None = None
    holds: int | None = None
    blownSaves: int | None = None
    earnedRuns: int | None = None
    whip: str | None = None
    battersFaced: int | None = None
    outs: int | None = None
    gamesPitched: int | None = None
    completeGames: int | None = None
    shutouts: int | None = None
    balls: int | None = None
    strikes: int | None = None
    strikePercentage: str | None = None
    hitBatsmen: int | None = None
    balks: int | None = None
    wildPitches: int | None = None
    pickoffs: int | None = None
    groundOutsToAirouts: str | None = None
    rbi: int | None = None
    winPercentage: str | None = None
    pitchesPerInning: str | None = None
    gamesFinished: int | None = None
    strikeoutWalkRatio: str | None = None
    strikeoutsPer9Inn: str | None = None
    walksPer9Inn: str | None = None
    hitsPer9Inn: str | None = None
    runsScoredPer9: str | None = None
    homeRunsPer9: str | None = None
    inheritedRunners: int | None = None
    inheritedRunnersScored: int | None = None
    catchersInterference: int | None = None
    sacBunts: int | None = None
    sacFlies: int | None = None
    passedBall: int | None = None
    popOuts: int | None = None
    lineOuts: int | None = None
    pitchesThrown: int | None = None


class PlayerSeasonFieldingStats(BaseModel):
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    caughtStealingPercentage: str | None = None
    assists: int | None = None
    putOuts: int | None = None
    errors: int | None = None
    chances: int | None = None
    fielding: str | None = None
    passedBall: int | None = None
    pickoffs: int | None = None
    gamesStarted: int | None = None


class PlayerSeasonStats(BaseModel):
    batting: PlayerSeasonBattingStats | None = None
    pitching: PlayerSeasonPitchingStats | None = None
    fielding: PlayerSeasonFieldingStats | None = None


class PlayerPerson(OfficialScorer):
    pass


class FieldListItem(BoxscoreInfoItem):
    pass


class TeamInfoItem(BaseModel):
    title: str | None = None
    fieldList: list[FieldListItem] | None = None


class Count(BaseModel):
    balls: int | None = None
    strikes: int | None = None
    outs: int | None = None


class PitchCoordinates(BaseModel):
    aY: float | None = None
    aZ: float | None = None
    pfxX: float | None = None
    pfxZ: float | None = None
    pX: float | None = None
    pZ: float | None = None
    vX0: float | None = None
    vY0: float | None = None
    vZ0: float | None = None
    x: float | None = None
    y: float | None = None
    x0: float | None = None
    y0: float | None = None
    z0: float | None = None
    aX: float | None = None


class HitCoordinates(BaseModel):
    coordX: float | None = None
    coordY: float | None = None


class FieldCoordinates(BaseModel):
    x: float | None = None
    y: float | None = None


class Breaks(BaseModel):
    breakAngle: float | None = None
    breakLength: float | None = None
    breakY: float | None = None
    breakVertical: float | None = None
    breakVerticalInduced: float | None = None
    breakHorizontal: float | None = None
    spinRate: int | None = None
    spinDirection: int | None = None


class PitchCall(BatSide):
    pass


class EventType(BatSide):
    pass


class StatType(BaseModel):
    displayName: str | None = None


class PitchData(BaseModel):
    startSpeed: float | None = None
    endSpeed: float | None = None
    strikeZoneTop: float | None = None
    strikeZoneBottom: float | None = None
    strikeZoneWidth: float | None = None
    strikeZoneDepth: float | None = None
    coordinates: PitchCoordinates | None = None
    breaks: Breaks | None = None
    zone: int | None = None
    typeConfidence: float | None = None
    plateTime: float | None = None
    extension: float | None = None


class HitData(BaseModel):
    launchSpeed: float | None = None
    launchAngle: float | None = None
    totalDistance: float | None = None
    trajectory: str | None = None
    hardness: str | None = None
    location: str | None = None
    coordinates: HitCoordinates | None = None


class PlayEventDetails(BaseModel):
    description: str | None = None
    event: str | None = None
    eventType: str | None = None
    awayScore: int | None = None
    homeScore: int | None = None
    isScoringPlay: bool | None = None
    isOut: bool | None = None
    hasReview: bool | None = None
    call: PitchCall | None = None
    code: str | None = None
    ballColor: str | None = None
    trailColor: str | None = None
    isInPlay: bool | None = None
    isStrike: bool | None = None
    isBall: bool | None = None
    type: EventType | None = None
    fromCatcher: bool | None = None
    disengagementNum: int | None = None
    runnerGoing: bool | None = None


class PlayerIdRef(OfficialVenue):
    pass


class Player(OfficialScorer):
    pass


class ReviewDetails(BaseModel):
    isOverturned: bool | None = None
    inProgress: bool | None = None
    reviewType: str | None = None
    challengeTeamId: int | None = None
    player: Player | None = None


class ReplacedPlayer(OfficialVenue):
    pass


class PlayEvent(BaseModel):
    details: PlayEventDetails | None = None
    count: Count | None = None
    index: int | None = None
    startTime: str | None = None
    endTime: str | None = None
    isPitch: bool | None = None
    type: str | None = None
    player: PlayerIdRef | None = None
    pitchData: PitchData | None = None
    playId: str | None = None
    pitchNumber: int | None = None
    hitData: HitData | None = None
    actionPlayId: str | None = None
    isBaseRunningPlay: bool | None = None
    isSubstitution: bool | None = None
    position: Position | None = None
    reviewDetails: ReviewDetails | None = None
    battingOrder: str | None = None
    replacedPlayer: ReplacedPlayer | None = None


class ResponsiblePitcher(OfficialVenue):
    pass


class RunnerDetails(BaseModel):
    event: str | None = None
    eventType: str | None = None
    movementReason: str | None = None
    runner: PersonRef | None = None
    responsiblePitcher: ResponsiblePitcher | None = None
    isScoringEvent: bool | None = None
    rbi: bool | None = None
    earned: bool | None = None
    teamUnearned: bool | None = None
    playIndex: int | None = None


class RunnerMovement(BaseModel):
    originBase: str | None = None
    start: str | None = None
    end: str | None = None
    outBase: str | None = None
    isOut: bool | None = None
    outNumber: int | None = None


class FieldingCredit(BaseModel):
    player: PlayerIdRef | None = None
    position: Position | None = None
    credit: str | None = None


class Runner(BaseModel):
    movement: RunnerMovement | None = None
    details: RunnerDetails | None = None
    credits: list[FieldingCredit] | None = None


class BatterHotColdZone(BaseModel):
    zone: str | None = None
    color: str | None = None
    temp: str | None = None
    value: str | None = None


class Splits(BaseModel):
    batter: str | None = None
    pitcher: str | None = None
    menOnBase: str | None = None


class PostOnSecond(OfficialScorer):
    pass


class PostOnFirst(OfficialScorer):
    pass


class PostOnThird(OfficialScorer):
    pass


class Group(StatType):
    pass


class Zone(BatterHotColdZone):
    pass


class HotColdZoneStat(BaseModel):
    name: str | None = None
    zones: list[Zone] | None = None


class Split(BaseModel):
    stat: HotColdZoneStat | None = Field(None, title="HotColdZoneStat")


class Stat(BaseModel):
    type: StatType | None = None
    group: Group | None = None
    exemptions: list[Any] | None = None
    splits: list[Split] | None = None


class BatterHotColdZoneStats(BaseModel):
    stats: list[Stat] | None = None


class Matchup(BaseModel):
    batter: Batter | None = None
    batSide: BatSide | None = None
    pitcher: Pitcher | None = None
    pitchHand: PitchHand | None = None
    batterHotColdZones: list[BatterHotColdZone] | None = None
    pitcherHotColdZones: list[Any] | None = None
    splits: Splits | None = None
    postOnSecond: PostOnSecond | None = None
    postOnFirst: PostOnFirst | None = None
    postOnThird: PostOnThird | None = None
    batterHotColdZoneStats: BatterHotColdZoneStats | None = None


class About(BaseModel):
    atBatIndex: int | None = None
    halfInning: str | None = None
    isTopInning: bool | None = None
    inning: int | None = None
    startTime: str | None = None
    endTime: str | None = None
    isComplete: bool | None = None
    isScoringPlay: bool | None = None
    hasReview: bool | None = None
    hasOut: bool | None = None
    captivatingIndex: int | None = None


class Result(BaseModel):
    type: str | None = None
    event: str | None = None
    eventType: str | None = None
    description: str | None = None
    rbi: int | None = None
    awayScore: int | None = None
    homeScore: int | None = None
    isOut: bool | None = None


class PlayerStatus(BatSide):
    pass


class HitTeam(BaseModel):
    springLeague: SpringLeague | None = None
    allStarStatus: str | None = None
    id: int | None = None
    name: str | None = None
    link: str | None = None


class LinescoreTeam(TeamVenue):
    pass


class PlayerGameStatus(BaseModel):
    isCurrentBatter: bool | None = None
    isCurrentPitcher: bool | None = None
    isOnBench: bool | None = None
    isSubstitute: bool | None = None


class GameDataTeams(BaseModel):
    away: GameTeam | None = None
    home: GameTeam | None = None


class Review(BaseModel):
    hasChallenges: bool | None = None
    away: ReviewCounts | None = None
    home: ReviewCounts | None = None


class AbsChallenges(BaseModel):
    hasChallenges: bool | None = None
    away: AbsChallengeCounts | None = None
    home: AbsChallengeCounts | None = None


class ProbablePitchers(BaseModel):
    away: PersonRef | None = None
    home: PersonRef | None = None


class MoundVisits(BaseModel):
    away: MoundVisitCounts | None = None
    home: MoundVisitCounts | None = None


class GameData(BaseModel):
    game: Game | None = None
    datetime: Datetime | None = None
    status: GameState | None = Field(None, title="GameState")
    teams: GameDataTeams | None = Field(None, title="GameDataTeams")
    players: GameDataPlayersDict | None = Field(None, title="GameDataPlayersDict")
    venue: GameVenue | None = Field(None, title="GameVenue")
    officialVenue: OfficialVenue | None = None
    weather: Weather | None = None
    gameInfo: GameInfo | None = None
    review: Review | None = None
    absChallenges: AbsChallenges | None = None
    flags: Flags | None = None
    alerts: list[Any] | None = None
    probablePitchers: ProbablePitchers | None = None
    officialScorer: OfficialScorer | None = None
    primaryDatacaster: PrimaryDatacaster | None = None
    moundVisits: MoundVisits | None = None


class AllPlay(BaseModel):
    result: Result | None = None
    about: About | None = None
    count: Count | None = None
    matchup: Matchup | None = None
    pitchIndex: list[int] | None = None
    actionIndex: list[int] | None = None
    runnerIndex: list[int] | None = None
    runners: list[Runner] | None = None
    playEvents: list[PlayEvent] | None = None
    playEndTime: str | None = None
    atBatIndex: int | None = None


class CurrentPlay(BaseModel):
    result: Result | None = None
    about: About | None = None
    count: Count | None = None
    matchup: Matchup | None = None
    pitchIndex: list[int] | None = None
    actionIndex: list[Any] | None = None
    runnerIndex: list[int] | None = None
    runners: list[Runner] | None = None
    playEvents: list[PlayEvent] | None = None
    playEndTime: str | None = None
    atBatIndex: int | None = None


class AwayItem(BaseModel):
    team: HitTeam | None = None
    inning: int | None = None
    pitcher: Pitcher | None = None
    batter: Batter | None = None
    coordinates: FieldCoordinates | None = None
    type: str | None = None
    description: str | None = None


class HomeItem(AwayItem):
    pass


class Hits(BaseModel):
    away: list[AwayItem] | None = None
    home: list[HomeItem] | None = None


class PlaysByInningItem(BaseModel):
    startIndex: int | None = None
    endIndex: int | None = None
    top: list[int] | None = None
    bottom: list[int] | None = None
    hits: Hits | None = None


class Plays(BaseModel):
    allPlays: list[AllPlay] | None = None
    currentPlay: CurrentPlay | None = None
    scoringPlays: list[int] | None = None
    playsByInning: list[PlaysByInningItem] | None = None


class Innings(BaseModel):
    num: int | None = None
    ordinalNum: str | None = None
    home: LinescoreInningHalf | None = None
    away: LinescoreInningHalf | None = None


class LinescoreTeams(BaseModel):
    home: LinescoreInningHalf | None = None
    away: LinescoreInningHalf | None = None


class Defense(BaseModel):
    pitcher: Pitcher | None = None
    catcher: Catcher | None = None
    first: First | None = None
    second: Second | None = None
    third: Third | None = None
    shortstop: Shortstop | None = None
    left: Left | None = None
    center: Center | None = None
    right: Right | None = None
    batter: Batter | None = None
    onDeck: OnDeck | None = None
    inHole: InHole | None = None
    battingOrder: int | None = None
    team: LinescoreTeam | None = None


class Offense(BaseModel):
    batter: Batter | None = None
    onDeck: OnDeck | None = None
    inHole: InHole | None = None
    pitcher: Pitcher | None = None
    battingOrder: int | None = None
    team: LinescoreTeam | None = None


class Linescore(BaseModel):
    currentInning: int | None = None
    currentInningOrdinal: str | None = None
    inningState: str | None = None
    inningHalf: str | None = None
    isTopInning: bool | None = None
    scheduledInnings: int | None = None
    innings: list[Innings] | None = None
    teams: LinescoreTeams | None = Field(None, title="LinescoreTeams")
    defense: Defense | None = None
    offense: Offense | None = None
    balls: int | None = None
    strikes: int | None = None
    outs: int | None = None


class TopPerformerPlayer(BaseModel):
    person: TopPerformerPerson | None = Field(None, title="TopPerformerPerson")
    jerseyNumber: str | None = None
    position: Position | None = None
    status: PlayerStatus | None = None
    parentTeamId: int | None = None
    stats: PlayerStats | None = None
    seasonStats: PlayerSeasonStats | None = None
    gameStatus: PlayerGameStatus | None = None
    allPositions: list[AllPosition] | None = None
    battingOrder: str | None = None


class TopPerformer(BaseModel):
    player: TopPerformerPlayer | None = Field(None, title="TopPerformerPlayer")
    type: str | None = None
    gameScore: int | None = None
    pitchingGameScore: int | None = None
    hittingGameScore: int | None = None


class BoxscorePlayer(BaseModel):
    person: PlayerPerson | None = Field(None, title="PlayerPerson")
    jerseyNumber: str | None = None
    position: Position | None = None
    status: PlayerStatus | None = None
    parentTeamId: int | None = None
    stats: PlayerStats | None = None
    seasonStats: PlayerSeasonStats | None = None
    gameStatus: PlayerGameStatus | None = None
    battingOrder: str | None = None
    allPositions: list[AllPosition] | None = None


class BoxscorePlayersDict(RootModel[dict[str, BoxscorePlayer] | None]):
    root: dict[str, BoxscorePlayer] | None = Field(None, title="BoxscorePlayersDict")


class BoxscoreTeam(BaseModel):
    team: HitTeam | None = None
    teamStats: TeamStats | None = None
    players: BoxscorePlayersDict | None = Field(None, title="BoxscorePlayersDict")
    batters: list[int] | None = None
    pitchers: list[int] | None = None
    bench: list[int] | None = None
    bullpen: list[int] | None = None
    battingOrder: list[int] | None = None
    info: list[TeamInfoItem] | None = None
    note: list[Any] | None = None


class BoxscoreTeams(BaseModel):
    away: BoxscoreTeam | None = None
    home: BoxscoreTeam | None = None


class Boxscore(BaseModel):
    teams: BoxscoreTeams | None = Field(None, title="BoxscoreTeams")
    officials: list[OfficialAssignment] | None = None
    info: list[BoxscoreInfoItem] | None = None
    pitchingNotes: list[str] | None = None
    topPerformers: list[TopPerformer] | None = None


class LiveData(BaseModel):
    plays: Plays | None = None
    linescore: Linescore | None = None
    boxscore: Boxscore | None = None
    decisions: Decisions | None = None
    leaders: Leaders | None = None


class GameFeed(BaseModel):
    copyright: str | None = None
    gamePk: int | None = None
    link: str | None = None
    metaData: MetaData | None = None
    gameData: GameData | None = None
    liveData: LiveData | None = None
