# generated by datamodel-codegen:
#   filename:  person.json
#   timestamp: 2026-05-07T13:14:34+00:00

from __future__ import annotations

from pydantic import BaseModel


class CurrentTeam(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None


class PrimaryPosition(BaseModel):
    code: str | None = None
    name: str | None = None
    type: str | None = None
    abbreviation: str | None = None


class BatSide(BaseModel):
    code: str | None = None
    description: str | None = None


class PitchHand(BatSide):
    pass


class Person(BaseModel):
    id: int | None = None
    fullName: str | None = None
    link: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    primaryNumber: str | None = None
    birthDate: str | None = None
    currentAge: int | None = None
    birthCity: str | None = None
    birthCountry: str | None = None
    height: str | None = None
    weight: int | None = None
    active: bool | None = None
    currentTeam: CurrentTeam | None = None
    primaryPosition: PrimaryPosition | None = None
    useName: str | None = None
    useLastName: str | None = None
    boxscoreName: str | None = None
    nickName: str | None = None
    gender: str | None = None
    isPlayer: bool | None = None
    isVerified: bool | None = None
    pronunciation: str | None = None
    mlbDebutDate: str | None = None
    batSide: BatSide | None = None
    pitchHand: PitchHand | None = None
    nameFirstLast: str | None = None
    nameSlug: str | None = None
    firstLastName: str | None = None
    lastFirstName: str | None = None
    lastInitName: str | None = None
    initLastName: str | None = None
    fullFMLName: str | None = None
    fullLFMName: str | None = None
    strikeZoneTop: float | None = None
    strikeZoneBottom: float | None = None


class PersonResponse(BaseModel):
    copyright: str | None = None
    people: list[Person] | None = None
