# generated by datamodel-codegen:
#   filename:  roster.json
#   timestamp: 2026-05-07T13:14:32+00:00

from __future__ import annotations

from pydantic import BaseModel


class PrimaryPosition(BaseModel):
    code: str | None = None
    name: str | None = None
    type: str | None = None
    abbreviation: str | None = None


class BatSide(BaseModel):
    code: str | None = None
    description: str | None = None


class PitchHand(BatSide):
    pass


class Person(BaseModel):
    id: int | None = None
    fullName: str | None = None
    link: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    primaryNumber: str | None = None
    birthDate: str | None = None
    currentAge: int | None = None
    birthCity: str | None = None
    birthCountry: str | None = None
    height: str | None = None
    weight: int | None = None
    active: bool | None = None
    primaryPosition: PrimaryPosition | None = None
    useName: str | None = None
    useLastName: str | None = None
    middleName: str | None = None
    boxscoreName: str | None = None
    gender: str | None = None
    nameMatrilineal: str | None = None
    isPlayer: bool | None = None
    isVerified: bool | None = None
    pronunciation: str | None = None
    mlbDebutDate: str | None = None
    batSide: BatSide | None = None
    pitchHand: PitchHand | None = None
    nameFirstLast: str | None = None
    nameSlug: str | None = None
    firstLastName: str | None = None
    lastFirstName: str | None = None
    lastInitName: str | None = None
    initLastName: str | None = None
    fullFMLName: str | None = None
    fullLFMName: str | None = None
    strikeZoneTop: float | None = None
    strikeZoneBottom: float | None = None
    nickName: str | None = None
    birthStateProvince: str | None = None
    draftYear: int | None = None


class Position(PrimaryPosition):
    pass


class Status(BatSide):
    pass


class RosterItem(BaseModel):
    person: Person | None = None
    jerseyNumber: str | None = None
    position: Position | None = None
    status: Status | None = None
    parentTeamId: int | None = None


class RosterResponse(BaseModel):
    copyright: str | None = None
    roster: list[RosterItem] | None = None
    link: str | None = None
    teamId: int | None = None
    rosterType: str | None = None
