# generated by datamodel-codegen:
#   filename:  schedule.json
#   timestamp: 2026-05-07T13:14:27+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Status(BaseModel):
    abstractGameState: str | None = None
    codedGameState: str | None = None
    detailedState: str | None = None
    statusCode: str | None = None
    startTimeTBD: bool | None = None
    abstractGameCode: str | None = None


class SpringLeague(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None
    abbreviation: str | None = None


class Venue(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None


class SpringVenue(BaseModel):
    id: int | None = None
    link: str | None = None


class League(Venue):
    pass


class Division(Venue):
    pass


class Sport(BaseModel):
    id: int | None = None
    link: str | None = None
    name: str | None = None


class Team(BaseModel):
    springLeague: SpringLeague | None = None
    allStarStatus: str | None = None
    id: int | None = None
    name: str | None = None
    link: str | None = None
    season: int | None = None
    venue: Venue | None = None
    springVenue: SpringVenue | None = None
    teamCode: str | None = None
    fileCode: str | None = None
    abbreviation: str | None = None
    teamName: str | None = None
    locationName: str | None = None
    firstYearOfPlay: str | None = None
    league: League | None = None
    division: Division | None = None
    sport: Sport | None = None
    shortName: str | None = None
    franchiseName: str | None = None
    clubName: str | None = None
    active: bool | None = None


class LeagueRecord(BaseModel):
    wins: int | None = None
    losses: int | None = None
    pct: str | None = None


class Away(BaseModel):
    team: Team | None = None
    leagueRecord: LeagueRecord | None = None
    score: int | None = None
    isWinner: bool | None = None
    splitSquad: bool | None = None
    seriesNumber: int | None = None
    springLeague: SpringLeague | None = None


class Team1(Team):
    pass


class Home(BaseModel):
    team: Team1 | None = None
    leagueRecord: LeagueRecord | None = None
    score: int | None = None
    isWinner: bool | None = None
    splitSquad: bool | None = None
    seriesNumber: int | None = None
    springLeague: SpringLeague | None = None


class Teams(BaseModel):
    away: Away | None = None
    home: Home | None = None


class Home1(BaseModel):
    runs: int | None = None
    hits: int | None = None
    errors: int | None = None
    leftOnBase: int | None = None


class Away1(Home1):
    pass


class Innings(BaseModel):
    num: int | None = None
    ordinalNum: str | None = None
    home: Home1 | None = None
    away: Away1 | None = None


class Home2(BaseModel):
    runs: int | None = None
    hits: int | None = None
    errors: int | None = None
    leftOnBase: int | None = None
    isWinner: bool | None = None


class Away2(Home2):
    pass


class Teams1(BaseModel):
    home: Home2 | None = None
    away: Away2 | None = None


class Pitcher(BaseModel):
    id: int | None = None
    fullName: str | None = None
    link: str | None = None


class Catcher(Pitcher):
    pass


class First(Pitcher):
    pass


class Second(Pitcher):
    pass


class Third(Pitcher):
    pass


class Shortstop(Pitcher):
    pass


class Left(Pitcher):
    pass


class Center(Pitcher):
    pass


class Right(Pitcher):
    pass


class Batter(Pitcher):
    pass


class OnDeck(Pitcher):
    pass


class InHole(Pitcher):
    pass


class Team2(Venue):
    pass


class Defense(BaseModel):
    pitcher: Pitcher | None = None
    catcher: Catcher | None = None
    first: First | None = None
    second: Second | None = None
    third: Third | None = None
    shortstop: Shortstop | None = None
    left: Left | None = None
    center: Center | None = None
    right: Right | None = None
    batter: Batter | None = None
    onDeck: OnDeck | None = None
    inHole: InHole | None = None
    battingOrder: int | None = None
    team: Team2 | None = None


class Offense(BaseModel):
    batter: Batter | None = None
    onDeck: OnDeck | None = None
    inHole: InHole | None = None
    second: Second | None = None
    pitcher: Pitcher | None = None
    battingOrder: int | None = None
    team: Team2 | None = None
    third: Third | None = None
    first: First | None = None


class Linescore(BaseModel):
    currentInning: int | None = None
    currentInningOrdinal: str | None = None
    inningState: str | None = None
    inningHalf: str | None = None
    isTopInning: bool | None = None
    scheduledInnings: int | None = None
    innings: list[Innings] | None = None
    teams: Teams1 | None = None
    defense: Defense | None = None
    offense: Offense | None = None
    balls: int | None = None
    strikes: int | None = None
    outs: int | None = None
    note: str | None = None


class Content(BaseModel):
    link: str | None = None


class Away3(BaseModel):
    used: int | None = None
    remaining: int | None = None


class Home3(Away3):
    pass


class Review(BaseModel):
    hasChallenges: bool | None = None
    away: Away3 | None = None
    home: Home3 | None = None


class Flags(BaseModel):
    noHitter: bool | None = None
    perfectGame: bool | None = None
    awayTeamNoHitter: bool | None = None
    awayTeamPerfectGame: bool | None = None
    homeTeamNoHitter: bool | None = None
    homeTeamPerfectGame: bool | None = None


class Game(BaseModel):
    gamePk: int | None = None
    gameGuid: str | None = None
    link: str | None = None
    gameType: str | None = None
    season: str | None = None
    gameDate: str | None = None
    officialDate: str | None = None
    status: Status | None = None
    teams: Teams | None = None
    linescore: Linescore | None = None
    venue: Venue | None = None
    content: Content | None = None
    isTie: bool | None = None
    gameNumber: int | None = None
    publicFacing: bool | None = None
    doubleHeader: str | None = None
    gamedayType: str | None = None
    tiebreaker: str | None = None
    calendarEventID: str | None = None
    seasonDisplay: str | None = None
    dayNight: str | None = None
    scheduledInnings: int | None = None
    reverseHomeAwayStatus: bool | None = None
    inningBreakLength: int | None = None
    gamesInSeries: int | None = None
    seriesGameNumber: int | None = None
    seriesDescription: str | None = None
    review: Review | None = None
    flags: Flags | None = None
    recordSource: str | None = None
    ifNecessary: str | None = None
    ifNecessaryDescription: str | None = None


class Date(BaseModel):
    date: str | None = None
    totalItems: int | None = None
    totalEvents: int | None = None
    totalGames: int | None = None
    totalGamesInProgress: int | None = None
    games: list[Game] | None = None
    events: list[Any] | None = None


class ScheduleResponse(BaseModel):
    copyright: str | None = None
    totalItems: int | None = None
    totalEvents: int | None = None
    totalGames: int | None = None
    totalGamesInProgress: int | None = None
    dates: list[Date] | None = None
