# generated by datamodel-codegen:
#   filename:  stats.json
#   timestamp: 2026-05-07T13:14:36+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Type(BaseModel):
    displayName: str | None = None


class Group(Type):
    pass


class Stat1(BaseModel):
    gamesPlayed: int | None = None
    groundOuts: int | None = None
    airOuts: int | None = None
    runs: int | None = None
    doubles: int | None = None
    triples: int | None = None
    homeRuns: int | None = None
    strikeOuts: int | None = None
    baseOnBalls: int | None = None
    intentionalWalks: int | None = None
    hits: int | None = None
    hitByPitch: int | None = None
    avg: str | None = None
    atBats: int | None = None
    obp: str | None = None
    slg: str | None = None
    ops: str | None = None
    caughtStealing: int | None = None
    stolenBases: int | None = None
    stolenBasePercentage: str | None = None
    caughtStealingPercentage: str | None = None
    groundIntoDoublePlay: int | None = None
    numberOfPitches: int | None = None
    plateAppearances: int | None = None
    totalBases: int | None = None
    rbi: int | None = None
    leftOnBase: int | None = None
    sacBunts: int | None = None
    sacFlies: int | None = None
    babip: str | None = None
    groundOutsToAirouts: str | None = None
    catchersInterference: int | None = None
    atBatsPerHomeRun: str | None = None
    # pitching fields
    era: str | None = None
    whip: str | None = None
    wins: int | None = None
    losses: int | None = None
    gamesPitched: int | None = None
    gamesStarted: int | None = None
    inningsPitched: str | None = None
    strikes: int | None = None


class Player(BaseModel):
    id: int | None = None
    fullName: str | None = None
    link: str | None = None


class Sport(BaseModel):
    id: int | None = None
    link: str | None = None
    abbreviation: str | None = None


class Team(BaseModel):
    id: int | None = None
    abbreviation: str | None = None


class Split(BaseModel):
    stat: Stat1 | None = None
    player: Player | None = None
    sport: Sport | None = None
    team: Team | None = None
    season: str | None = None
    gameType: str | None = None
    numTeams: int | None = None
    numLeagues: int | None = None


class Stat(BaseModel):
    type: Type | None = None
    group: Group | None = None
    exemptions: list[Any] | None = None
    splits: list[Split] | None = None


class StatsResponse(BaseModel):
    copyright: str | None = None
    stats: list[Stat] | None = None
