# generated by datamodel-codegen:
#   filename:  teams.json
#   timestamp: 2026-05-07T13:14:29+00:00

from __future__ import annotations

from pydantic import BaseModel


class SpringLeague(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None
    abbreviation: str | None = None


class Venue(BaseModel):
    id: int | None = None
    name: str | None = None
    link: str | None = None


class SpringVenue(BaseModel):
    id: int | None = None
    link: str | None = None


class League(Venue):
    pass


class Division(Venue):
    pass


class Sport(BaseModel):
    id: int | None = None
    link: str | None = None
    name: str | None = None


class Team(BaseModel):
    springLeague: SpringLeague | None = None
    allStarStatus: str | None = None
    id: int | None = None
    name: str | None = None
    link: str | None = None
    season: int | None = None
    venue: Venue | None = None
    springVenue: SpringVenue | None = None
    teamCode: str | None = None
    fileCode: str | None = None
    abbreviation: str | None = None
    teamName: str | None = None
    locationName: str | None = None
    firstYearOfPlay: str | None = None
    league: League | None = None
    division: Division | None = None
    sport: Sport | None = None
    shortName: str | None = None
    franchiseName: str | None = None
    clubName: str | None = None
    active: bool | None = None


class TeamsResponse(BaseModel):
    copyright: str | None = None
    teams: list[Team] | None = None
